server:
  port: 8080

spring:
  application:
    name: federation-agricole-api

app:
  datasource:
    url: jdbc:postgresql://localhost:5432/agricole_federation
    username: postgres
    password: admin123