spring:
  application:
    name: TD-Final-OAS

  datasource:
    url: jdbc:postgresql://localhost:5432/db_agricole_federation
    username: postgres
    password: jose/2007
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

# API key
api:
  security:
    key: agri-secure-key