INSERT INTO collectivity (id, name, location, agricultural_specialty, creation_date, federation_approval, president_id, vice_president_id, treasurer_id, secretary_id) VALUES
                                                                                                                                                                           ('col-1', 'Ny Tantsaha Malagasy', 'Antananarivo', 'Riziculture', '2022-01-15', TRUE, NULL, NULL, NULL, NULL),
                                                                                                                                                                           ('col-2', 'Vokatra Tsara', 'Fianarantsoa', 'Maraîchage', '2022-06-10', TRUE, NULL, NULL, NULL, NULL),
                                                                                                                                                                           ('col-3', 'Harena Voajanahary', 'Toamasina', 'Culture de vanille', '2023-03-20', TRUE, NULL, NULL, NULL, NULL);

INSERT INTO member (id, collectivity_id, first_name, last_name, birth_date, gender, address, profession, phone_number, email, adhesion_date, occupation, registration_fee_paid, membership_dues_paid) VALUES
                                                                                                                                                                                                          ('MEM-1', 'col-1', 'Rakoto', 'Andriamaro', '1980-05-10', 'MALE', '12 Rue Indépendance, Antananarivo', 'Agriculteur', '34011', 'rakoto.andriamaro@email.mg', '2022-01-15', 'PRESIDENT', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-2', 'col-1', 'Voahangy', 'Rasoa', '1985-08-22', 'FEMALE', '45 Av Liberté, Antananarivo', 'Agricultrice', '34012', 'voahangy.rasoa@email.mg', '2022-01-15', 'VICE_PRESIDENT', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-3', 'col-1', 'Hery', 'Rakotondrabe', '1978-11-03', 'MALE', '8 Rue du Marché, Antananarivo', 'Cultivateur', '34013', 'hery.rakotondrabe@email.mg', '2022-01-15', 'TREASURER', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-4', 'col-1', 'Lalao', 'Raharison', '1990-02-17', 'FEMALE', '23 Cité Ampefiloha, Antananarivo', 'Secrétaire', '34014', 'lalao.raharison@email.mg', '2022-01-15', 'SECRETARY', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-5', 'col-1', 'Fidy', 'Randria', '1988-07-30', 'MALE', '56 Rue Pasteur, Antananarivo', 'Agriculteur', '34015', 'fidy.randria@email.mg', '2022-01-15', 'SENIOR', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-6', 'col-1', 'Miora', 'Rasolofonirina', '1992-04-11', 'FEMALE', '3 Allée des Jacarandas, Tana', 'Agricultrice', '34016', 'miora.rasolofonirina@email.mg', '2022-01-15', 'SENIOR', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-7', 'col-1', 'Tiana', 'Razafindrabe', '1995-09-25', 'MALE', '17 Rue Rainitovo, Antananarivo', 'Étudiant', '34017', 'tiana.razafindrabe@email.mg', '2022-02-01', 'SENIOR', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-8', 'col-1', 'Nasolo', 'Rabemananjara', '1997-12-05', 'MALE', '99 Av de France, Antananarivo', 'Cultivateur', '34018', 'nasolo.rabemananjara@email.mg', '2022-03-10', 'SENIOR', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-9', 'col-1', 'Hasina', 'Randriamasy', '20-06-18', 'FEMALE', '7 Rue Solombavambahoaka, Tana', 'Agricultrice', '34019', 'hasina.randriamasy@email.mg', '2022-04-15', 'SENIOR', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-010', 'col-1', 'Toky', 'Ramaroson', '21-03-22', 'MALE', '34 Cité Universitaire, Tana', 'Étudiant', '3401010', 'toky.ramaroson@email.mg', '2022-05-01', 'JUNIOR', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-011', 'col-1', 'Anja', 'Ratsimbazafy', '22-08-14', 'FEMALE', '21 Rue Ny Haja, Antananarivo', 'Étudiante', '3401011', 'anja.ratsimbazafy@email.mg', '2022-06-10', 'JUNIOR', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-012', 'col-1', 'Tafita', 'Rakotondrazaka', '1999-11-30', 'MALE', '60 Bd Ratsimilaho, Antananarivo', 'Cultivateur', '3401012', 'tafita.rakotondrazaka@email.mg', '2022-07-20', 'JUNIOR', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-013', 'col-2', 'Solo', 'Andriantsoa', '1975-01-08', 'MALE', '5 Rue de la Paix, Fianarantsoa', 'Agriculteur', '34021', 'solo.andriantsoa@email.mg', '2022-06-10', 'PRESIDENT', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-014', 'col-2', 'Noro', 'Rafaralahimana', '1983-05-19', 'FEMALE', '12 Av Gallieni, Fianarantsoa', 'Agricultrice', '34022', 'noro.rafaralahimana@email.mg', '2022-06-10', 'VICE_PRESIDENT', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-015', 'col-2', 'Mamy', 'Razafindrakoto', '1980-09-14', 'MALE', '33 Rue Rainandriamampandry, Fiana', 'Comptable', '34023', 'mamy.razafindrakoto@email.mg', '2022-06-10', 'TREASURER', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-016', 'col-2', 'Fanja', 'Rakotoniary', '1987-03-27', 'FEMALE', '8 Cité Ambalakely, Fianarantsoa', 'Secrétaire', '34024', 'fanja.rakotoniary@email.mg', '2022-06-10', 'SECRETARY', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-017', 'col-2', 'Lanto', 'Andrianaivo', '1991-07-06', 'MALE', '45 Rue Ny Fitiavana, Fiana', 'Agriculteur', '34025', 'lanto.andrianaivo@email.mg', '2022-06-10', 'SENIOR', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-018', 'col-2', 'Vatosoa', 'Raharinoro', '1993-12-21', 'FEMALE', '19 Av de la Réunification, Fiana', 'Cultivatrice', '34026', 'vatosoa.raharinoro@email.mg', '2022-06-10', 'SENIOR', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-019', 'col-2', 'Mendrika', 'Rasoamanarivo', '1989-04-09', 'MALE', '27 Rue Ranaivo, Fianarantsoa', 'Agriculteur', '34027', 'mendrika.rasoamanarivo@email.mg', '2022-07-01', 'SENIOR', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-020', 'col-2', 'Tahiry', 'Rakotonirina', '1996-10-15', 'FEMALE', '11 Cité Tanambao, Fianarantsoa', 'Étudiante', '34028', 'tahiry.rakotonirina@email.mg', '2022-08-05', 'SENIOR', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-021', 'col-2', 'Njaka', 'Andriamahefa', '1998-02-28', 'MALE', '3 Rue du Progrès, Fianarantsoa', 'Cultivateur', '34029', 'njaka.andriamahefa@email.mg', '2022-09-12', 'SENIOR', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-022', 'col-2', 'Diary', 'Rajaonah', '21-06-17', 'FEMALE', '50 Bd Lyautey, Fianarantsoa', 'Étudiante', '3402010', 'diary.rajaonah@email.mg', '2022-10-20', 'JUNIOR', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-023', 'col-2', 'Tsiry', 'Andrianjafy', '23-08-04', 'MALE', '6 Rue Ny Fanantenana, Fiana', 'Étudiant', '3402011', 'tsiry.andrianjafy@email.mg', '2022-11-01', 'JUNIOR', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-024', 'col-3', 'Benja', 'Rabenilaina', '1977-03-12', 'MALE', '14 Rue de la Mer, Toamasina', 'Agriculteur', '34031', 'benja.rabenilaina@email.mg', '2023-03-20', 'PRESIDENT', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-025', 'col-3', 'Mirana', 'Ralaimihoatra', '1984-07-25', 'FEMALE', '8 Av de l''Indépendance, Toamasina', 'Agricultrice', '34032', 'mirana.ralaimihoatra@email.mg', '2023-03-20', 'VICE_PRESIDENT', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-026', 'col-3', 'Erick', 'Rasolondraibe', '1981-11-18', 'MALE', '22 Rue du Port, Toamasina', 'Comptable', '34033', 'erick.rasolondraibe@email.mg', '2023-03-20', 'TREASURER', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-027', 'col-3', 'Zo', 'Rakotomalala', '1990-05-07', 'FEMALE', '37 Cité Ambalakely, Toamasina', 'Secrétaire', '34034', 'zo.rakotomalala@email.mg', '2023-03-20', 'SECRETARY', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-028', 'col-3', 'Haja', 'Andriantsalama', '1986-08-30', 'MALE', '5 Rue Rainitovo, Toamasina', 'Cultivateur', '34035', 'haja.andriantsalama@email.mg', '2023-03-20', 'SENIOR', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-029', 'col-3', 'Saholy', 'Rakotondravo', '1994-01-14', 'FEMALE', '60 Bd Ratsimilaho, Toamasina', 'Agricultrice', '34036', 'saholy.rakotondravo@email.mg', '2023-03-20', 'SENIOR', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-030', 'col-3', 'Feno', 'Andriamasy', '1992-04-22', 'MALE', '18 Rue Ny Tanindrazana, Toamasina', 'Agriculteur', '34037', 'feno.andriamasy@email.mg', '2023-04-01', 'SENIOR', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-031', 'col-3', 'Kanto', 'Ramarolahy', '1988-09-03', 'FEMALE', '9 Av Gallieni, Toamasina', 'Cultivatrice', '34038', 'kanto.ramarolahy@email.mg', '2023-04-15', 'SENIOR', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-032', 'col-3', 'Nivo', 'Razafimaharo', '1997-12-28', 'MALE', '43 Rue du Marché, Toamasina', 'Cultivateur', '34039', 'nivo.razafimaharo@email.mg', '2023-05-10', 'SENIOR', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-033', 'col-3', 'Rindra', 'Rakotozafy', '20-03-16', 'FEMALE', '25 Cité Tanambao, Toamasina', 'Étudiante', '3403010', 'rindra.rakotozafy@email.mg', '2023-06-01', 'JUNIOR', TRUE, TRUE),
                                                                                                                                                                                                          ('MEM-034', 'col-3', 'Arj', 'Andriamandroso', '22-07-09', 'MALE', '7 Rue du Progrès, Toamasina', 'Étudiant', '3403011', 'arj.andriamandroso@email.mg', '2023-07-15', 'JUNIOR', TRUE, TRUE);

UPDATE collectivity SET president_id = 'MEM-1', vice_president_id = 'MEM-2', treasurer_id = 'MEM-3', secretary_id = 'MEM-4' WHERE id = 'col-1';
UPDATE collectivity SET president_id = 'MEM-013', vice_president_id = 'MEM-014', treasurer_id = 'MEM-015', secretary_id = 'MEM-016' WHERE id = 'col-2';
UPDATE collectivity SET president_id = 'MEM-024', vice_president_id = 'MEM-025', treasurer_id = 'MEM-026', secretary_id = 'MEM-027' WHERE id = 'col-3';

UPDATE collectivity SET annual_dues = 20 WHERE id = 'col-1';
UPDATE collectivity SET annual_dues = 15 WHERE id = 'col-2';
UPDATE collectivity SET annual_dues = 18 WHERE id = 'col-3';

INSERT INTO sponsorship (candidate_id, sponsor_id, relationship_nature) VALUES
                                                                            ('MEM-010', 'MEM-5', 'collègues'), ('MEM-010', 'MEM-6', 'Amis'),
                                                                            ('MEM-011', 'MEM-7', 'Famille'), ('MEM-011', 'MEM-017', 'collègues'),
                                                                            ('MEM-012', 'MEM-8', 'Voisins'), ('MEM-012', 'MEM-9', 'Amis'),
                                                                            ('MEM-022', 'MEM-017', 'Amis'), ('MEM-022', 'MEM-018', 'Famille'),
                                                                            ('MEM-023', 'MEM-019', 'collègues'), ('MEM-023', 'MEM-020', 'Amis'),
                                                                            ('MEM-033', 'MEM-028', 'Voisins'), ('MEM-033', 'MEM-029', 'Amis'),
                                                                            ('MEM-034', 'MEM-030', 'Famille'), ('MEM-034', 'MEM-031', 'Voisins');

INSERT INTO membership_fee (id, collectivity_id, label, amount, fee_type, active, created_at) VALUES
                                                                                                  ('FEE-1', 'col-1', 'Cotisation mensuelle col-1', 2, 'MONTHLY', TRUE, '2022-01-15'),
                                                                                                  ('FEE-2', 'col-1', 'Cotisation annuelle col-1', 20, 'ANNUAL', TRUE, '2022-01-15'),
                                                                                                  ('FEE-3', 'col-2', 'Cotisation mensuelle col-2', 150, 'MONTHLY', TRUE, '2022-06-10'),
                                                                                                  ('FEE-4', 'col-2', 'Cotisation annuelle col-2', 15, 'ANNUAL', TRUE, '2022-06-10'),
                                                                                                  ('FEE-5', 'col-3', 'Cotisation mensuelle col-3', 180, 'MONTHLY', TRUE, '2023-03-20'),
                                                                                                  ('FEE-6', 'col-3', 'Cotisation annuelle col-3', 18, 'ANNUAL', TRUE, '2023-03-20');

INSERT INTO member_payment (id, member_id, membership_fee_id, amount, payment_date, payment_mode) VALUES
                                                                                                      ('PAY-1', 'MEM-1', 'FEE-2', 20, '2025-01-10', 'BANK_TRANSFER'),
                                                                                                      ('PAY-2', 'MEM-2', 'FEE-2', 20, '2025-01-12', 'MOBILE_MONEY'),
                                                                                                      ('PAY-3', 'MEM-3', 'FEE-2', 20, '2025-01-15', 'CASH'),
                                                                                                      ('PAY-4', 'MEM-5', 'FEE-2', 20, '2025-02-01', 'BANK_TRANSFER'),
                                                                                                      ('PAY-5', 'MEM-013', 'FEE-4', 15, '2025-01-08', 'BANK_TRANSFER'),
                                                                                                      ('PAY-6', 'MEM-014', 'FEE-4', 15, '2025-01-09', 'MOBILE_MONEY');

INSERT INTO activity (id, collectivity_id, title, activity_date, activity_type, attendance_requirement) VALUES
                                                                                                            ('act-1-mar', 'col-1', 'AG1', '2026-03-07', 'MONTHLY_ASSEMBLY', 'ALL'),
                                                                                                            ('act-1-apr', 'col-1', 'AG1', '2026-04-04', 'MONTHLY_ASSEMBLY', 'ALL'),
                                                                                                            ('act-2', 'col-1', 'Formation de base', '2026-03-08', 'JUNIOR_TRAINING', 'JUNIORS_ONLY'),
                                                                                                            ('act-3-mar', 'col-2', 'AG2', '2026-03-08', 'MONTHLY_ASSEMBLY', 'ALL'),
                                                                                                            ('act-3-apr', 'col-2', 'AG2', '2026-04-05', 'MONTHLY_ASSEMBLY', 'ALL'),
                                                                                                            ('act-4', 'col-2', 'Formation de base', '2026-03-15', 'JUNIOR_TRAINING', 'JUNIORS_ONLY'),
                                                                                                            ('act-5', 'col-2', 'Perfectionnement', '2026-04-30', 'EXCEPTIONAL', 'SPECIFIC'),
                                                                                                            ('act-6-mar', 'col-3', 'AG3', '2026-03-06', 'MONTHLY_ASSEMBLY', 'ALL'),
                                                                                                            ('act-6-apr', 'col-3', 'AG3', '2026-04-03', 'MONTHLY_ASSEMBLY', 'ALL'),
                                                                                                            ('act-7', 'col-3', 'Formation de base', '2026-03-25', 'JUNIOR_TRAINING', 'JUNIORS_ONLY');

INSERT INTO activity_attendance (activity_id, member_id, status) VALUES
                                                                     ('act-1-mar', 'MEM-1', 'PRESENT'), ('act-1-mar', 'MEM-2', 'PRESENT'), ('act-1-mar', 'MEM-3', 'PRESENT'), ('act-1-mar', 'MEM-4', 'PRESENT'),
                                                                     ('act-1-mar', 'MEM-5', 'PRESENT'), ('act-1-mar', 'MEM-6', 'PRESENT'), ('act-1-mar', 'MEM-7', 'ABSENT'), ('act-1-mar', 'MEM-8', 'ABSENT');

INSERT INTO activity_attendance (activity_id, member_id, status) VALUES
                                                                     ('act-1-apr', 'MEM-1', 'PRESENT'), ('act-1-apr', 'MEM-2', 'PRESENT'), ('act-1-apr', 'MEM-3', 'ABSENT'), ('act-1-apr', 'MEM-4', 'ABSENT'),
                                                                     ('act-1-apr', 'MEM-5', 'PRESENT'), ('act-1-apr', 'MEM-6', 'PRESENT'), ('act-1-apr', 'MEM-7', 'PRESENT'), ('act-1-apr', 'MEM-8', 'PRESENT');

INSERT INTO activity_attendance (activity_id, member_id, status) VALUES
                                                                     ('act-3-mar', 'MEM-013', 'PRESENT'), ('act-3-mar', 'MEM-014', 'PRESENT'), ('act-3-mar', 'MEM-015', 'ABSENT'), ('act-3-mar', 'MEM-016', 'ABSENT'),
                                                                     ('act-3-mar', 'MEM-017', 'PRESENT'), ('act-3-mar', 'MEM-018', 'PRESENT'), ('act-3-mar', 'MEM-019', 'PRESENT'), ('act-3-mar', 'MEM-020', 'PRESENT');

INSERT INTO activity_attendance (activity_id, member_id, status) VALUES
                                                                     ('act-3-apr', 'MEM-013', 'PRESENT'), ('act-3-apr', 'MEM-014', 'PRESENT'), ('act-3-apr', 'MEM-015', 'ABSENT'), ('act-3-apr', 'MEM-016', 'PRESENT'),
                                                                     ('act-3-apr', 'MEM-017', 'PRESENT'), ('act-3-apr', 'MEM-018', 'PRESENT'), ('act-3-apr', 'MEM-019', 'PRESENT'), ('act-3-apr', 'MEM-020', 'ABSENT');

INSERT INTO activity_attendance (activity_id, member_id, status) VALUES
                                                                     ('act-5', 'MEM-013', 'PRESENT'), ('act-5', 'MEM-014', 'PRESENT'), ('act-5', 'MEM-015', 'PRESENT'), ('act-5', 'MEM-016', 'ABSENT');

INSERT INTO activity_attendance (activity_id, member_id, status) VALUES
                                                                     ('act-6-mar', 'MEM-024', 'PRESENT'), ('act-6-mar', 'MEM-025', 'PRESENT'), ('act-6-mar', 'MEM-026', 'PRESENT'), ('act-6-mar', 'MEM-027', 'PRESENT'),
                                                                     ('act-6-mar', 'MEM-028', 'PRESENT'), ('act-6-mar', 'MEM-029', 'PRESENT'), ('act-6-mar', 'MEM-030', 'ABSENT'), ('act-6-mar', 'MEM-031', 'ABSENT');

INSERT INTO activity_attendance (activity_id, member_id, status) VALUES
                                                                     ('act-6-apr', 'MEM-024', 'PRESENT'), ('act-6-apr', 'MEM-025', 'PRESENT'), ('act-6-apr', 'MEM-026', 'ABSENT'), ('act-6-apr', 'MEM-027', 'ABSENT'),
                                                                     ('act-6-apr', 'MEM-028', 'PRESENT'), ('act-6-apr', 'MEM-029', 'PRESENT'), ('act-6-apr', 'MEM-030', 'ABSENT'), ('act-6-apr', 'MEM-032', 'PRESENT'),
                                                                     ('act-6-apr', 'MEM-1', 'PRESENT');
