INSERT INTO members (id, first_name, last_name, birth_date, gender, address, profession, phone_number, email, occupation, adhesion_date, registration_fee_paid, membership_dues_paid) VALUES
                                                                                                                                                                                          ('m001', 'Jean', 'Rakoto', '1980-05-15', 'MALE', 'Lot 123 Ankadifotsy, Antananarivo', 'Agriculteur', '0341234567', 'jean.rakoto@federation.mg', 'SENIOR', '2020-01-15', true, true),
                                                                                                                                                                                          ('m002', 'Marie', 'Rabe', '1985-08-22', 'FEMALE', 'Lot 456 Ambohimanarina, Antananarivo', 'Éleveur', '0331234567', 'marie.rabe@federation.mg', 'SENIOR', '2020-03-10', true, true),
                                                                                                                                                                                          ('m003', 'Paul', 'Rasoa', '1975-11-30', 'MALE', 'Lot 789 Ivandry, Antananarivo', 'Exportateur', '0321234567', 'paul.rasoa@federation.mg', 'SENIOR', '2019-06-20', true, true),
                                                                                                                                                                                          ('m004', 'Jeanne', 'Razafy', '1990-02-14', 'FEMALE', 'Lot 101 Andravoahangy, Antananarivo', 'Technicien agricole', '0349876543', 'jeanne.razafy@federation.mg', 'SENIOR', '2021-02-01', true, true),
                                                                                                                                                                                          ('m005', 'Pierre', 'Andria', '1988-07-03', 'MALE', 'Lot 202 Analamahitsy, Antananarivo', 'Ingénieur agronome', '0339876543', 'pierre.andria@federation.mg', 'SENIOR', '2021-05-15', true, true),
                                                                                                                                                                                          ('m006', 'Sophie', 'Rakotomalala', '1992-09-18', 'FEMALE', 'Lot 303 Ambatobe, Antananarivo', 'Commerçant', '0329876543', 'sophie.rakotomalala@federation.mg', 'SENIOR', '2022-01-10', true, true),
                                                                                                                                                                                          ('m007', 'Michel', 'Rakotonirina', '1983-12-25', 'MALE', 'Lot 404 Ankorondrano, Antananarivo', 'Transporteur', '0345551234', 'michel.rakotonirina@federation.mg', 'SENIOR', '2021-08-20', true, true),
                                                                                                                                                                                          ('m008', 'Claire', 'Randria', '1995-04-08', 'FEMALE', 'Lot 505 Mahamasina, Antananarivo', 'Vétérinaire', '0335551234', 'claire.randria@federation.mg', 'SENIOR', '2022-03-05', true, true),
                                                                                                                                                                                          ('m009', 'Luc', 'Rakotoarison', '1978-06-12', 'MALE', 'Lot 606 Andohalo, Antananarivo', 'Chercheur', '0325551234', 'luc.rakotoarison@federation.mg', 'SENIOR', '2019-11-15', true, true),
                                                                                                                                                                                          ('m010', 'Chantal', 'Razanadrakoto', '1986-10-20', 'FEMALE', 'Lot 707 Isoraka, Antananarivo', 'Consultant', '0346667890', 'chantal.razanadrakoto@federation.mg', 'SENIOR', '2022-06-30', true, true),
                                                                                                                                                                                          ('m011', 'Robert', 'Rakotovao', '1982-09-12', 'MALE', 'Lot 111 Ampefiloha, Antananarivo', 'Agriculteur', '0341112233', 'robert.rakotovao@federation.mg', 'PRESIDENT', '2020-07-01', true, true),
                                                                                                                                                                                          ('m012', 'Aline', 'Rasoarimanana', '1987-12-03', 'FEMALE', 'Lot 222 Antanimena, Antananarivo', 'Commerçante', '0332223344', 'aline.rasoarimanana@federation.mg', 'TREASURER', '2021-09-15', true, true),
                                                                                                                                                                                          ('m013', 'Jacques', 'Rakotondrabe', '1979-04-18', 'MALE', 'Lot 333 Andavamamba, Antananarivo', 'Transporteur', '0323334455', 'jacques.rakotondrabe@federation.mg', 'SECRETARY', '2020-11-20', true, true),
                                                                                                                                                                                          ('m014', 'Henri', 'Rabemananjara', '1993-01-05', 'MALE', 'Lot 808 Faravohitra, Antananarivo', 'Apprenti agriculteur', '0336667890', 'henri.rabemananjara@federation.mg', 'JUNIOR', '2025-11-15', true, true),
                                                                                                                                                                                          ('m015', 'Yvette', 'Ravaoarimanana', '1991-03-28', 'FEMALE', 'Lot 909 67ha, Antananarivo', 'Apprentie éleveur', '0326667890', 'yvette.ravaoarimanana@federation.mg', 'JUNIOR', '2025-12-10', true, true);

INSERT INTO collectivities (id, name, location, specialty, creation_date, federation_approval, annual_membership_dues) VALUES
                                                                                                                           ('c001', 'Collectivité Agricole Antananarivo Centre', 'Antananarivo', 'Riziculture', '2023-01-01', true, 200000.00),
                                                                                                                           ('c002', 'Collectivité Agricole Toamasina Est', 'Toamasina', 'Vanille', '2023-06-15', true, 250000.00);

UPDATE members SET collectivity_id = 'c001' WHERE id IN ('m001', 'm002', 'm003', 'm004', 'm005', 'm006', 'm007', 'm008', 'm009', 'm010', 'm014', 'm015');
UPDATE members SET collectivity_id = 'c002' WHERE id IN ('m011', 'm012', 'm013');

INSERT INTO collectivity_structures (id, collectivity_id, president_id, vice_president_id, treasurer_id, secretary_id, mandate_year, start_date, end_date) VALUES
                                                                                                                                                               ('cs001', 'c001', 'm011', 'm001', 'm012', 'm013', 2026, '2026-01-01', '2026-12-31'),
                                                                                                                                                               ('cs002', 'c002', 'm001', 'm002', 'm003', 'm004', 2026, '2026-01-01', '2026-12-31');

INSERT INTO referees (id, member_id, referee_id, relationship) VALUES
                                                                   ('r001', 'm014', 'm001', 'FAMILLE'),
                                                                   ('r002', 'm014', 'm002', 'COLLEGUE'),
                                                                   ('r003', 'm014', 'm005', 'AMI'),
                                                                   ('r004', 'm015', 'm006', 'FAMILLE'),
                                                                   ('r005', 'm015', 'm007', 'COLLEGUE'),
                                                                   ('r006', 'm005', 'm011', 'COLLEGUE'),
                                                                   ('r007', 'm006', 'm012', 'AMI');

INSERT INTO mandates (id, member_id, collectivity_id, role, mandate_year, start_date, end_date, is_active) VALUES
                                                                                                               ('md001', 'm011', 'c001', 'PRESIDENT', 2026, '2026-01-01', '2026-12-31', true),
                                                                                                               ('md002', 'm001', 'c001', 'VICE_PRESIDENT', 2026, '2026-01-01', '2026-12-31', true),
                                                                                                               ('md003', 'm012', 'c001', 'TREASURER', 2026, '2026-01-01', '2026-12-31', true),
                                                                                                               ('md004', 'm013', 'c001', 'SECRETARY', 2026, '2026-01-01', '2026-12-31', true),
                                                                                                               ('md005', 'm011', 'c001', 'PRESIDENT', 2025, '2025-01-01', '2025-12-31', false),
                                                                                                               ('md006', 'm001', 'c001', 'VICE_PRESIDENT', 2025, '2025-01-01', '2025-12-31', false);

INSERT INTO accounts (id, collectivity_id, account_type, account_holder_name, bank_name, mobile_service, account_number, phone_number, balance) VALUES
                                                                                                                                                    ('acc001', 'c001', 'CASH', NULL, NULL, NULL, NULL, NULL, 500000.00),
                                                                                                                                                    ('acc002', 'c001', 'BANK', 'Collectivité Antananarivo Centre', 'BFV', NULL, '12345678901234567890123', NULL, 2000000.00),
                                                                                                                                                    ('acc003', 'c001', 'BANK', 'Collectivité Antananarivo Centre', 'MCB', NULL, '98765432109876543210987', NULL, 1500000.00),
                                                                                                                                                    ('acc004', 'c001', 'MOBILE_MONEY', 'Jean Rakoto', NULL, 'ORANGE_MONEY', NULL, '0341234567', 300000.00),
                                                                                                                                                    ('acc005', 'c001', 'MOBILE_MONEY', 'Marie Rabe', NULL, 'MVOLA', NULL, '0331234567', 200000.00),
                                                                                                                                                    ('acc006', 'c001', 'MOBILE_MONEY', 'Paul Rasoa', NULL, 'AIRTEL_MONEY', NULL, '0321234567', 150000.00),
                                                                                                                                                    ('acc007', 'c002', 'CASH', NULL, NULL, NULL, NULL, NULL, 300000.00),
                                                                                                                                                    ('acc008', 'c002', 'BANK', 'Collectivité Toamasina Est', 'BOA', NULL, '11112222333344445555666', NULL, 1000000.00);

INSERT INTO contributions (id, name, collectivity_id, amount, frequency, is_mandatory, description) VALUES
                                                                                                        ('cot001', 'Cotisation annuelle 2026', 'c001', 200000.00, 'ANNUAL', true, 'Cotisation annuelle obligatoire'),
                                                                                                        ('cot002', 'Cotisation mensuelle - Janvier', 'c001', 20000.00, 'MONTHLY', true, 'Cotisation mensuelle de janvier'),
                                                                                                        ('cot003', 'Cotisation mensuelle - Février', 'c001', 20000.00, 'MONTHLY', true, 'Cotisation mensuelle de février'),
                                                                                                        ('cot004', 'Cotisation mensuelle - Mars', 'c001', 20000.00, 'MONTHLY', true, 'Cotisation mensuelle de mars'),
                                                                                                        ('cot005', 'Foire Agricole 2026', 'c001', 50000.00, 'PUNCTUAL', false, 'Contribution pour participation à la foire'),
                                                                                                        ('cot006', 'Cotisation annuelle 2026', 'c002', 250000.00, 'ANNUAL', true, 'Cotisation annuelle obligatoire'),
                                                                                                        ('cot007', 'Formation Vanille', 'c002', 30000.00, 'PUNCTUAL', false, 'Formation sur la culture de la vanille');

INSERT INTO payments (id, member_id, contribution_id, account_id, amount, payment_date, payment_method, reference_number) VALUES
                                                                                                                              ('pay001', 'm001', 'cot001', 'acc002', 200000.00, '2026-01-15', 'BANK_TRANSFER', 'VIR-2026-001'),
                                                                                                                              ('pay002', 'm002', 'cot001', 'acc002', 200000.00, '2026-01-20', 'BANK_TRANSFER', 'VIR-2026-002'),
                                                                                                                              ('pay003', 'm003', 'cot001', 'acc003', 200000.00, '2026-01-10', 'BANK_TRANSFER', 'VIR-2026-003'),
                                                                                                                              ('pay004', 'm004', 'cot001', 'acc004', 200000.00, '2026-01-25', 'MOBILE_MONEY', 'OM-2026-001'),
                                                                                                                              ('pay005', 'm005', 'cot001', 'acc005', 200000.00, '2026-01-30', 'MOBILE_MONEY', 'MV-2026-001'),
                                                                                                                              ('pay006', 'm006', 'cot002', 'acc001', 20000.00, '2026-01-05', 'CASH', NULL),
                                                                                                                              ('pay007', 'm007', 'cot002', 'acc001', 20000.00, '2026-01-05', 'CASH', NULL),
                                                                                                                              ('pay008', 'm008', 'cot003', 'acc001', 20000.00, '2026-02-05', 'CASH', NULL),
                                                                                                                              ('pay009', 'm009', 'cot003', 'acc001', 20000.00, '2026-02-05', 'CASH', NULL),
                                                                                                                              ('pay010', 'm014', NULL, 'acc001', 50000.00, '2025-11-15', 'CASH', NULL),
                                                                                                                              ('pay011', 'm015', NULL, 'acc001', 50000.00, '2025-12-10', 'CASH', NULL),
                                                                                                                              ('pay012', 'm014', 'cot001', 'acc004', 200000.00, '2025-11-15', 'MOBILE_MONEY', 'OM-2025-089'),
                                                                                                                              ('pay013', 'm015', 'cot001', 'acc005', 200000.00, '2025-12-10', 'MOBILE_MONEY', 'MV-2025-102');

INSERT INTO activities (id, collectivity_id, title, description, activity_type, is_mandatory, target_audience, scheduled_date, start_time, end_time, location, created_by) VALUES
                                                                                                                                                                               ('act001', 'c001', 'Assemblée générale - Janvier', 'Bilan mensuel et perspectives', 'MONTHLY_MEETING', true, 'ALL', '2026-01-14', '09:00', '12:00', 'Salle Ankadifotsy', 'm011'),
                                                                                                                                                                               ('act002', 'c001', 'Assemblée générale - Février', 'Bilan mensuel et perspectives', 'MONTHLY_MEETING', true, 'ALL', '2026-02-11', '09:00', '12:00', 'Salle Ankadifotsy', 'm011'),
                                                                                                                                                                               ('act003', 'c001', 'Assemblée générale - Mars', 'Bilan mensuel et perspectives', 'MONTHLY_MEETING', true, 'ALL', '2026-03-11', '09:00', '12:00', 'Salle Ankadifotsy', 'm011'),
                                                                                                                                                                               ('act004', 'c001', 'Formation Juniors - Techniques de base', 'Formation obligatoire pour nouveaux membres', 'JUNIOR_TRAINING', true, 'JUNIORS', '2026-01-28', '14:00', '17:00', 'Centre Ambohimanarina', 'm004'),
                                                                                                                                                                               ('act005', 'c001', 'Formation Juniors - Irrigation', 'Techniques d''irrigation moderne', 'JUNIOR_TRAINING', true, 'JUNIORS', '2026-02-25', '14:00', '17:00', 'Centre Ambohimanarina', 'm004'),
                                                                                                                                                                               ('act006', 'c001', 'Atelier Riziculture Moderne', 'Formation exceptionnelle ouverte à tous', 'EXCEPTIONAL', false, 'ALL', '2026-03-15', '10:00', '16:00', 'Ivandry', 'm011'),
                                                                                                                                                                               ('act007', 'c002', 'Assemblée générale - Janvier', 'Bilan mensuel', 'MONTHLY_MEETING', true, 'ALL', '2026-01-21', '09:00', '12:00', 'Salle Toamasina', 'm001'),
                                                                                                                                                                               ('act008', 'c002', 'Formation Vanille', 'Culture et exportation', 'EXCEPTIONAL', false, 'ALL', '2026-02-18', '09:00', '16:00', 'Centre Toamasina', 'm001');

INSERT INTO attendances (id, activity_id, member_id, is_present, is_excused, excuse_reason, is_visitor, visitor_collectivity_id) VALUES
                                                                                                                                     ('att001', 'act001', 'm001', true, false, NULL, false, NULL),
                                                                                                                                     ('att002', 'act001', 'm002', true, false, NULL, false, NULL),
                                                                                                                                     ('att003', 'act001', 'm003', true, false, NULL, false, NULL),
                                                                                                                                     ('att004', 'act001', 'm004', true, false, NULL, false, NULL),
                                                                                                                                     ('att005', 'act001', 'm005', false, true, 'Maladie', false, NULL),
                                                                                                                                     ('att006', 'act001', 'm006', true, false, NULL, false, NULL),
                                                                                                                                     ('att007', 'act001', 'm007', true, false, NULL, false, NULL),
                                                                                                                                     ('att008', 'act001', 'm014', true, false, NULL, false, NULL),
                                                                                                                                     ('att009', 'act001', 'm015', true, false, NULL, false, NULL),
                                                                                                                                     ('att010', 'act001', 'm011', true, false, NULL, true, 'c002'),
                                                                                                                                     ('att011', 'act002', 'm001', true, false, NULL, false, NULL),
                                                                                                                                     ('att012', 'act002', 'm002', true, false, NULL, false, NULL),
                                                                                                                                     ('att013', 'act002', 'm014', true, false, NULL, false, NULL),
                                                                                                                                     ('att014', 'act002', 'm015', false, true, 'Déplacement', false, NULL),
                                                                                                                                     ('att015', 'act004', 'm014', true, false, NULL, false, NULL),
                                                                                                                                     ('att016', 'act004', 'm015', true, false, NULL, false, NULL),
                                                                                                                                     ('att017', 'act005', 'm014', true, false, NULL, false, NULL),
                                                                                                                                     ('att018', 'act005', 'm015', false, false, NULL, false, NULL);

INSERT INTO federation (id, president_id, vice_president_id, treasurer_id, secretary_id, mandate_start_date, mandate_end_date, is_active) VALUES
    ('fed001', 'm011', 'm001', 'm012', 'm013', '2025-01-01', '2026-12-31', true);